config/routes.rb
AssessmentNg::Application.routes.draw do
  root to: 'home#home'
  resources :customers, only: [:new,:create,:index,:show]
  resources :orders, only: [:new,:create,:index, :show]

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :first_name, :last_name
  has_many :orders
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :customer_id, :price
  belongs_to :customer

  def price_string
    reformat_price(self.price)
  end

  def reformat_price(price)
    price_string = price.to_s
    chars_after_decimal = nil;
    count_chars = false;
    
    price_string.each_char do |c|
      if c.to_s == '.'
        count_chars = true;
        chars_after_decimal = 0;
      elsif count_chars == true
        chars_after_decimal += 1;
      end
    end

    if chars_after_decimal == 1
      price_string += '0'
    elsif chars_after_decimal > 2
      chars_to_delete = chars_after_decimal - 2
      temp_price = price_string.reverse
      temp_price.slice!(0..chars_to_delete-1)
      price_string = temp_price.reverse
    end
    price_string
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  respond_to :html, :json, :xml

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(params[:customer])
    flash[:success] = "Customer created!" if @customer.save
    respond_with(@customer)
  end

  def show
    @customer = Customer.find(params[:id])
    respond_with(@customer)
  end

  def index
    @customers = Customer.all
    respond_with(@customers)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  respond_to :html, :json, :xml

  def new
    @order = Order.new
  end

  def create 
    @order = Order.new(params[:order])
    flash[:success] = "Order confirmed!" if @order.save
    respond_with(@order)
  end

  def show
    @order = Order.find(params[:id])
    respond_with(@order)
  end
  
  def index 
    @orders = Order.all
    respond_with(@orders)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/customers/index.html.erb
<h1>Customer List</h1>

<ul>
  <% @customers.each do |customer| %>
  <% name_string = customer.last_name + ', ' + customer.first_name %>
  <li><%= link_to name_string, customer %>
  </li>
  <% end %>
</ul>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= form_for(@customer) do |f| %>

<%=f.label :first_name %>
<%=f.text_field :first_name %>

<%= f.label :last_name %>
<%= f.text_field :last_name %>
    
<%= f.submit "Create Customer", class: "btn btn-large btn-primary" %>
<% end %>

app/views/customers/show.html.erb
<h1><%= @customer.first_name %> <%= @customer.last_name %></h1>
<p>Customer ID: <%= @customer.id %></p>

<% order_string = 'order' %>
<% if @customer.orders.count != 1 %>
<% order_string += 's' %>
<% end %>
<p><%= @customer.orders.count %> <%= order_string %></p>

app/views/home/home.html.erb
<h1>Home Page</h1>
<br>
<%= link_to "New Customer", new_customer_path %>
<%= link_to "Customers", customers_path %>
<br>
<%= link_to "New Order", new_order_path %>
<%= link_to "Orders", orders_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AssessmentNg</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to "Home", root_path %>
<%= yield %>

</body>
</html>

app/views/orders/index.html.erb
<h1>Order List</h1>
<ul>
  <% @orders.each do |order| %>
  <% order_string =  "Order ID: " + order.id.to_s + " " +
     "Price: $" + order.price_string %>
  <li><%= link_to order_string, order_path(order) %></li>
  <% end %>
</ul>
  

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= form_for(@order) do |f| %>

<%=f.label 'Customer ID' %>
<%=f.text_field :customer_id %>

<%= f.label :price %>
<%= f.text_field :price %>

<%= f.submit "Place Order", class: "btn btn-large btn-primary" %>
<% end %>

app/views/orders/show.html.erb
<h1>Order ID: <%= @order.id %></h1>
<p>$<%= @order.price_string %></p>
<p>Customer ID: <%= @order.customer_id %></p>